# Generated by Django 6.0.4 on 2026-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seed_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('accepted', 'Accepte'), ('refused', 'Refuse'), ('in_progress', 'En cours'), ('waiting', 'En attente'), ('resolved', 'Resolu'), ('closed', 'Ferme')], default='new', max_length=20, verbose_name='Statut'),
        ),
    ]
